name: Generate and Commit Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: List Files
        run: ls

      - name: Generate readme.txt
        run: echo "Generated documentation" > readme.txt

      - name: List Files 2
        run: ls
